import React from "react";
import {
  Plus,
  ArrowLeft,
  Camera,
  MessageCircle,
  MessagesSquare,
  X,
  XCircle,
  Heart,
  Home,
  Image as ImageIcon,
  LogOut,
  Music,
  Send,
  Share2,
  Trash2,
  TrendingUp,
  Wallet,
  Sun,
  Moon,
  Instagram,
  Youtube,
  Chrome,
  HelpCircle,
  Download,
  Hourglass,
  Video,
  User,
  Sparkles,
  Award,
  Star,
  Flame,
  Zap,
  Activity,
  Eye,
  Lock,
  RefreshCw,
  Play,
  Pause,
  AtSign,
  Pencil,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Volume2,
  VolumeX,
  Edit3,
  Undo2,
  Brush,
  Smile,
  CloudOff,
  CloudUpload,
  Wand2,
  SwitchCamera,
  Target,
  MapPin,
  CalendarDays,
  Repeat,
  ListChecks,
  ShieldCheck,
  Users,
  Globe,
  Settings,
  UserPlus,
  Briefcase,
  Building2,
  QrCode,
  Clock,
  Mic,
  LucideIcon,
} from "lucide-react-native";

type IconProps = {
  name: string;
  size?: number;
  color?: string;
  style?: any;
};

const map: Record<string, LucideIcon> = {
  add: Plus,
  "arrow-back": ArrowLeft,
  camera: Camera,
  "camera-outline": Camera,
  "chatbubble-outline": MessageCircle,
  "chatbubbles-outline": MessagesSquare,
  close: X,
  heart: Heart,
  "heart-outline": Heart,
  home: Home,
  "image-outline": ImageIcon,
  "log-out-outline": LogOut,
  "logo-google": Chrome,
  "logo-instagram": Instagram,
  "logo-youtube": Youtube,
  moon: Moon,
  "musical-notes": Music,
  send: Send,
  "share-outline": Share2,
  sunny: Sun,
  "trash-outline": Trash2,
  "trending-up": TrendingUp,
  wallet: Wallet,
  "wallet-outline": Wallet,
  "download-outline": Download,
  download: Download,
  "hourglass-outline": Hourglass,
  videocam: Video,
  "videocam-outline": Video,
  person: User,
  "person-outline": User,
  "person-circle": User,
  sparkles: Sparkles,
  "sparkles-outline": Sparkles,
  trophy: Award,
  "trophy-outline": Award,
  star: Star,
  "star-outline": Star,
  flame: Flame,
  "flame-outline": Flame,
  flash: Zap,
  "flash-outline": Zap,
  pulse: Activity,
  "pulse-outline": Activity,
  eye: Eye,
  "eye-outline": Eye,
  "lock-closed": Lock,
  "lock-closed-outline": Lock,
  refresh: RefreshCw,
  "refresh-outline": RefreshCw,
  play: Play,
  "play-outline": Play,
  pause: Pause,
  "pause-outline": Pause,
  at: AtSign,
  pencil: Pencil,
  "create-outline": Edit3,
  "checkmark-circle": CheckCircle,
  "checkmark-circle-outline": CheckCircle,
  "close-circle": XCircle,
  "close-circle-outline": XCircle,
  "chevron-back": ChevronLeft,
  "chevron-back-outline": ChevronLeft,
  "chevron-forward": ChevronRight,
  "chevron-forward-outline": ChevronRight,
  trash: Trash2,
  "volume-high": Volume2,
  "volume-mute": VolumeX,
  "musical-note": Music,
  "musical-notes-outline": Music,
  mic: Mic,
  "mic-outline": Mic,
  time: Clock,
  "time-outline": Clock,
  stop: XCircle,
  "stop-circle": XCircle,
  "stop-circle-outline": XCircle,
  "images-outline": ImageIcon,
  images: ImageIcon,
  "arrow-undo": Undo2,
  "arrow-undo-outline": Undo2,
  brush: Brush,
  "brush-outline": Brush,
  "happy-outline": Smile,
  happy: Smile,
  "cloud-offline-outline": CloudOff,
  "cloud-offline": CloudOff,
  "cloud-upload-outline": CloudUpload,
  "cloud-upload": CloudUpload,
  "color-wand-outline": Wand2,
  "color-wand": Wand2,
  "camera-reverse": SwitchCamera,
  "camera-reverse-outline": SwitchCamera,
  "sync": SwitchCamera,
  "sync-outline": SwitchCamera,
  "radio-button-on": Target,
  "radio-button-on-outline": Target,
  locate: Target,
  "locate-outline": Target,
  "location-outline": MapPin,
  location: MapPin,
  calendar: CalendarDays,
  "calendar-outline": CalendarDays,
  repeat: Repeat,
  "repeat-outline": Repeat,
  "list-checks": ListChecks,
  "shield-check": ShieldCheck,
  people: Users,
  "people-outline": Users,
  globe: Globe,
  "globe-outline": Globe,
  settings: Settings,
  "settings-outline": Settings,
  "person-add": UserPlus,
  "person-add-outline": UserPlus,
  "paper-plane-outline": Send,
  briefcase: Briefcase,
  "briefcase-outline": Briefcase,
  business: Building2,
  "business-outline": Building2,
  "qr-code": QrCode,
  "qr-code-outline": QrCode,
};

const filledNames = new Set(["heart"]);

function IoniconsComponent({ name, size = 24, color, style }: IconProps) {
  const Icon = map[name] || HelpCircle;
  const isFilled = filledNames.has(name);
  return (
    <Icon
      size={size}
      color={color}
      fill={isFilled ? color : "none"}
      style={style}
    />
  );
}

IoniconsComponent.font = {};

export const Ionicons = IoniconsComponent;
export default IoniconsComponent;
